server:
#  servlet:
#    context-path: /
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATASOURCE_URL}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
